### ISSUE TITLE
두번째 교육(Swift) 

### ISSUE THREAD

**Issue by shingagyoung** [shingagyoung/task#1]
- [x] 2-1 서버에서 DicomStudy 및 DicomSeries 데이터를 받아와 Table 등의 형식으로 출력하기 #2 
- [x]  2-2 DicomSeries 선택 시 series의 volumeFilePath 내의 이미지(axial) 출력하기 #8

- [ ] 2-3 Nrrd 데이터를 Sagittal, Coronal로 이미지 변환 및 WWL 적용 #10
