### ISSUE TITLE
2-1. 서버에서 DicomStudy 및 DicomSeries 데이터를 받아와 Table 등의 형식으로 출력하기

### ISSUE THREAD

**Issue by shingagyoung** [shingagyoung/task#2]
- #1 에 대한 하위이슈 2-1입니다.

### 서버에서 DicomStudy 및 DicomSeries 데이터를 받아와 Table 등의 형식으로 출력하고자 합니다. 
아래 명시된 작업 순서대로 진행 예정입니다. 

- [x] DicomStudy, DicomSeries 정보에 매핑되는 데이터 구조 추가 #3 

- [x] 웹 API 를 이용하여 DicomStudy 및 이에 속한 DicomSeries 정보를 얻는 기능 구현 + debug console  등으로 출력 #4 

- [ ] Table View 등을 이용해 keyword 로 검색한 DicomStudy 및 하위 DicomSeries 를 UI로 표현 #5

**Comment by alkee-skia** [comment]
참고로 다른 sub-issue 들로 이루어진 issue 에서는 [task-list 형태](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#task-lists) 로 작성하시는게 편리할 수 있습니다. (진행상황 체크)
